apiVersion: v1
kind: Service
metadata:
  name: chatbot-server-service
spec:
  selector:
    app: chatbot-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer
